# Generated by Django 3.2.6 on 2023-10-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='description',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='title',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='url',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='search_result',
            field=models.JSONField(null=True),
        ),
    ]
